version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"

  test:
    build: .
    command: npm test
    depends_on:
      - app
    environment:
      - BASE_URL=http://app:3000 