version: '3'
services:
  app:
    build: .
    image: todo-backend-app
    command: npm start
    ports:
      - "3000:3000"

  test:
    image: todo-backend-app
    command: npm test
    depends_on:
      - app
    environment:
      - API_URL=http://app:3000 