name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test with Docker Compose
        run: |
          docker compose up --build --exit-code-from test
          docker compose down

      - name: Push to Docker Hub
        if: success()
        run: |
          docker tag todo-backend-app ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest