name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test in Docker
      run: |
        docker build -t todo-app .
        docker run -p 3000:3000 --rm todo-app npm test 