name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT || 3000 }}
      NODE_ENV: ${{ secrets.NODE_ENV || 'test' }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create env file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env.test
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.test

    - name: Start server and run tests
      run: |
        npm start & # Start the server in background
        sleep 5 # Wait for server to start
        npm test # Run the tests 