name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test in Docker
      run: |
        docker build -t todo-app .
        docker run -d -p 3000:3000 --name todo-app-container todo-app
        sleep 5

    - name: Run Tests
      run: docker exec todo-app-container npm test

    - name: Stop and Remove Container
      run: docker stop todo-app-container